-- MySQL Script generated by MySQL Workbench
-- Sun Nov 11 17:12:11 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema timesheet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema timesheet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `timesheet` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `timesheet` ;

-- -----------------------------------------------------
-- Table `timesheet`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`employees` (
  `emp_number` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isAdmin` BIT(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`emp_number`),
  UNIQUE INDEX `empNumber_UNIQUE` (`emp_number` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `timesheet`.`timesheet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`timesheet` (
  `emp_number` INT(10) UNSIGNED NOT NULL,
  `end_week` DATE NOT NULL,
  `overtime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `flextime` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `timesheet_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`timesheet_id`),
  UNIQUE INDEX `timesheet_id_UNIQUE` (`timesheet_id` ASC) VISIBLE,
  INDEX `timesheet_empNumber_idx` (`emp_number` ASC) VISIBLE,
  CONSTRAINT `timesheet_empNumber`
    FOREIGN KEY (`emp_number`)
    REFERENCES `timesheet`.`employees` (`emp_number`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `timesheet`.`timesheet_row`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `timesheet`.`timesheet_row` (
  `project_id` INT(10) UNSIGNED NOT NULL,
  `work_package` VARCHAR(45) NOT NULL,
  `notes` VARCHAR(200) NULL DEFAULT NULL,
  `sun_hours` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `mon_hours` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `tue_hours` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `wed_hours` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `thu_hours` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `fri_hours` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `sat_hours` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `timesheet_id` INT(10) UNSIGNED NOT NULL,
  `timesheet_row_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`timesheet_row_id`),
  UNIQUE INDEX `timesheet_row_id_UNIQUE` (`timesheet_row_id` ASC) VISIBLE,
  INDEX `timesheetRow_timesheetID_idx` (`timesheet_id` ASC) VISIBLE,
  CONSTRAINT `timesheetRow_timesheetID`
    FOREIGN KEY (`timesheet_id`)
    REFERENCES `timesheet`.`timesheet` (`timesheet_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
